name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '00 2 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked as stale due to inactivty.'
        stale-pr-message: 'This pull request has been marked as stale due to inactivty.'
        stale-issue-label: 'stale-issue'
        stale-pr-label: 'stale-pull-request'
